"""peract demo: single-episode rollout driven by a WebSocket policy server.

Purpose
-------
Connects to a server speaking the `policy_websocket` protocol (default
companion: `tests/test_random_policy_server.py`), runs ONE RLBench episode
with per-step logging, then exits. No dataset, no checkpoint, no
success-rate aggregation — this is the "show me one run" sibling of
run_eval.py. Use it to sanity-check a new policy server or to watch a
single rollout interactively.

Each invocation creates `<log_dir>/demo/<task>--<YYYYMMDD_HHMMSS>/` so that
downstream video / trajectory dumps land in a per-run directory rather than
overwriting earlier runs. A light `demo.log` mirrors stdout — enough to
grep after the fact without reaching for a full eval pipeline.

Video saving (`--save_video`) enables RLBench's front camera and writes a
single MP4 to the run_dir. Requires a working offscreen GL context; the
headless compose profile (QT_QPA_PLATFORM=offscreen) can't provide one, so
camera init will crash and the script falls back to no-video. Use the X11
profile or `xvfb-run -a ...` for real capture.

Example
-------
    # Terminal A — start the companion random-policy server
    python tests/test_random_policy_server.py --port 8000

    # Terminal B — run a single episode against it
    python scripts/run_demo.py --policy_server_addr localhost:8000 \\
        --task open_drawer --n-steps 20

    # Inspect the per-run directory afterwards
    ls logs/demo/open_drawer--*/

Generated by benchmark-env-generator (IL Category).
"""
import argparse
import atexit
import os
import signal
import sys
from datetime import datetime
from typing import Optional

import numpy as np

from policy_websocket import WebsocketClientPolicy


SMOKE_ENV_ID = "open_drawer"


def log(msg: str, log_file: Optional["os.PathLike"] = None) -> None:
    """Print to stdout and, if open, also write to a log file (flushed each call)."""
    print(msg)
    if log_file is not None and not log_file.closed:
        log_file.write(msg + "\n")
        log_file.flush()


def build_env(task_name: str, headless: bool = True, enable_front_camera: bool = False):
    from rlbench.environment import Environment
    from rlbench.action_modes.action_mode import MoveArmThenGripper
    from rlbench.action_modes.arm_action_modes import EndEffectorPoseViaPlanning
    from rlbench.action_modes.gripper_action_modes import Discrete
    from rlbench.observation_config import ObservationConfig
    import rlbench.tasks as rlbench_tasks

    cls_name = "".join(w.capitalize() for w in task_name.split("_"))
    task_cls = getattr(rlbench_tasks, cls_name)

    obs_config = ObservationConfig()
    obs_config.set_all(False)
    obs_config.joint_positions = True
    obs_config.gripper_open = True
    if enable_front_camera:
        obs_config.front_camera.rgb = True

    env = Environment(
        action_mode=MoveArmThenGripper(EndEffectorPoseViaPlanning(), Discrete()),
        obs_config=obs_config,
        headless=headless,
    )
    env.launch()
    return env, env.get_task(task_cls)


def _obs_to_payload(obs):
    payload = {}
    if getattr(obs, "joint_positions", None) is not None:
        payload["joint_positions"] = np.asarray(obs.joint_positions, dtype=np.float32)
    if getattr(obs, "gripper_open", None) is not None:
        payload["gripper_open"] = float(obs.gripper_open)
    return payload


def main():
    parser = argparse.ArgumentParser(
        description=f"Single-episode demo against a WS policy server on RLBench.")
    parser.add_argument("--policy_server_addr", required=True,
                        help="host:port of the WebSocket policy server")
    parser.add_argument("--task", type=str, default=SMOKE_ENV_ID)
    parser.add_argument("--n-steps", type=int, default=10)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--log_dir", type=str, default="./logs",
                        help="Parent dir for per-run demo outputs (created if missing)")
    parser.add_argument("--save_video", action="store_true",
                        help="Record RLBench front_camera and write demo.mp4 to run_dir. "
                             "Requires X11 profile or xvfb — fails on headless (QT offscreen).")
    parser.add_argument("--video_fps", type=int, default=30)
    args = parser.parse_args()

    # ---- Set up run directory + log file ----
    date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join(args.log_dir, "demo", f"{args.task}--{date_str}")
    os.makedirs(run_dir, exist_ok=True)
    log_path = os.path.join(run_dir, "demo.log")
    log_file = open(log_path, "w")

    def _cleanup(signum=None, frame=None):
        try:
            if not log_file.closed:
                log_file.close()
        finally:
            sys.stdout.flush()
            sys.stderr.flush()
        if signum is not None:
            os._exit(1)

    signal.signal(signal.SIGINT, _cleanup)
    signal.signal(signal.SIGTERM, _cleanup)
    atexit.register(lambda: None if log_file.closed else log_file.close())

    log("=" * 60, log_file)
    log("peract demo", log_file)
    log("=" * 60, log_file)
    for k, v in sorted(vars(args).items()):
        log(f"  {k}: {v}", log_file)
    log(f"  run_dir: {run_dir}", log_file)
    log("=" * 60, log_file)
    log("", log_file)

    host, port = args.policy_server_addr.split(":")
    client = WebsocketClientPolicy(host=host, port=int(port))
    meta = client.get_server_metadata()
    log(f"server metadata: {meta}", log_file)

    np.random.seed(args.seed)

    save_video = args.save_video
    try:
        env, task = build_env(args.task, headless=True, enable_front_camera=save_video)
    except Exception as e:
        if save_video:
            log(
                f"[warn] enabling front_camera crashed env.launch ({type(e).__name__}: {e}); "
                f"disabling --save_video and retrying. "
                f"Use X11 profile or xvfb-run for video capture.",
                log_file,
            )
            save_video = False
            env, task = build_env(args.task, headless=True, enable_front_camera=False)
        else:
            raise

    try:
        descriptions, obs = task.reset()
        log(f"task={args.task}  descriptions={descriptions[:1]}", log_file)

        total_reward = 0.0
        steps_done = 0
        frames = []
        for i in range(args.n_steps):
            payload = _obs_to_payload(obs)
            response = client.infer(payload)
            action = np.asarray(response["actions"], dtype=np.float32)
            try:
                obs, reward, terminate = task.step(action)
                total_reward += float(reward)
                steps_done += 1
                if save_video:
                    frame = getattr(obs, "front_rgb", None)
                    if frame is not None:
                        frames.append(np.asarray(frame, dtype=np.uint8))
                log(f"step {i}: reward={reward} terminate={terminate}", log_file)
                if terminate:
                    break
            except Exception as e:
                log(f"step {i}: {type(e).__name__} (random action, expected)", log_file)

        log("", log_file)
        log(
            f"demo finished: {steps_done}/{args.n_steps} steps executed, "
            f"total_reward={total_reward:.3f}",
            log_file,
        )
        if save_video and frames:
            try:
                import imageio
                mp4 = os.path.join(run_dir, "demo.mp4")
                writer = imageio.get_writer(
                    mp4, fps=args.video_fps, format="FFMPEG", codec="libx264")
                for f in frames:
                    writer.append_data(f)
                writer.close()
                log(f"saved video: {mp4}", log_file)
            except Exception as e:
                log(f"[warn] imageio write failed: {type(e).__name__}: {e}", log_file)
        log(f"log_file: {log_path}", log_file)
    finally:
        try:
            client.close()
        except Exception:
            pass
        env.shutdown()
        if not log_file.closed:
            log_file.close()


if __name__ == "__main__":
    main()
